### ISSUE TITLE
TypeError: 'NoneType' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by wingsofovnia** [Jhruzik/ImmobilienScout24.de-Crawler#3]
```
$ python3 --version
Python 3.6.3
$ python3 immoscrap.py --type=f --payment=r
Fehler beim Einlesen in BeautifulSoup
Fehler beim Loop
Traceback (most recent call last):
  File "immoscrap.py", line 147, in <module>
    immo_crawl(site_list)#start crawler
  File "immoscrap.py", line 137, in immo_crawl
    for i in range(1,max_dict[site]):
TypeError: 'NoneType' object cannot be interpreted as an integer
```

**Comment by wingsofovnia** [comment]
`pip install lxml` fixes the problem. Please improve error logging so it's easier to find out such errors.
